version: 0.0
os: linux

files:
  - source: ./target/webservice-0.0.1-SNAPSHOT.jar
    destination: /tmp
  - source: ./cloudwatch-config.json
    destination: /tmp
file_exists_behavior: OVERWRITE

hooks:
  AfterInstall:
    - location: ./codedeploy/afterInstall.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: ./codedeploy/applicationStart.sh
      timeout: 180
      runas: root
  ApplicationStop:
    - location: ./codedeploy/beforeInstall.sh
      timeout: 180
      runas: root
