AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  MySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: 'csye6225-webapp-topic'
      FifoTopic: 'false'
      Subscription:
        - Endpoint: arn:aws:lambda:us-west-2:574594835790:function:vemailFunction
          Protocol: lambda
