name: CI to build AMI

on:
  pull_request:
    branches: [main]
    types: [closed]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  packer_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.3
      - name: build with maven
        run: mvn -B package --file pom.xml
      - name: package
        run: mvn package
      - name: check file
        run: ls -al target
      - name: Build ami
        run: PACKER_LOG=1 packer build ami.json
